# Generated by Django 5.1.2 on 2024-11-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='started',
            field=models.BooleanField(default=0),
        ),
    ]
