# Generated by Django 5.1.2 on 2024-11-26 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_matches_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='client.robot'),
        ),
    ]
