# Generated by Django 5.1.2 on 2024-11-26 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_match_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='client.robot'),
        ),
    ]
